### ISSUE TITLE
ModuleNotFoundError: No module named 'chinese_converter'

### ISSUE THREAD

**Issue by boyesm** [timmy6figures/autoanki#2]
```Traceback (most recent call last):
  File "/Users/malcolm/Projects/autoanki/src/autoanki/AutoAnki.py", line 4, in <module>
    from autoanki.Dictionary.YellowBridgeDictionary import YellowBridgeDictionary
  File "/Users/malcolm/Projects/autoanki/venv/lib/python3.11/site-packages/autoanki/__init__.py", line 1, in <module>
    from .AutoAnki import AutoAnki
  File "/Users/malcolm/Projects/autoanki/venv/lib/python3.11/site-packages/autoanki/AutoAnki.py", line 4, in <module>
    from autoanki.Dictionary.YellowBridgeDictionary import YellowBridgeDictionary
  File "/Users/malcolm/Projects/autoanki/venv/lib/python3.11/site-packages/autoanki/Dictionary/__init__.py", line 1, in <module>
    from .CEDictionary import CEDictionary 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/malcolm/Projects/autoanki/venv/lib/python3.11/site-packages/autoanki/Dictionary/CEDictionary.py", line 8, in <module>
    import chinese_converter
ModuleNotFoundError: No module named 'chinese_converter'```

**Comment by jarviscog** [comment]
Added to requirements.txt in next version
